### ISSUE TITLE
"mkdocs build" fails on Ubuntu 14.10

### ISSUE THREAD

**Issue by vilbara** [GluuFederation/docs#6]
Hi,

Building the docs fails on Ubuntu 14.10:

```
$ mkdocs build
Building documentation to directory: site
Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 9, in <module>
    load_entry_point('mkdocs==0.11', 'console_scripts', 'mkdocs')()
  File "/usr/local/lib/python2.7/dist-packages/mkdocs/main.py", line 60, in run_main
    main(cmd, args=sys.argv[2:], options=dict(opts))
  File "/usr/local/lib/python2.7/dist-packages/mkdocs/main.py", line 36, in main
    build(config, clean_site_dir=clean_site_dir)
  File "/usr/local/lib/python2.7/dist-packages/mkdocs/build.py", line 266, in build
    build_pages(config)
  File "/usr/local/lib/python2.7/dist-packages/mkdocs/build.py", line 229, in build_pages
    output_content = template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "./theme/mkdocs/base.html", line 27, in top-level template code
    {% if config.google_analytics %}
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 397, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'config' is undefined
```

Any tips?

Thanks!
Vilmantas

**Comment by willow9886** [comment]
Vilmantas,

We finally fixed this issue. Docs have been updated here: [https://github.com/GluuFederation/docs](https://github.com/GluuFederation/docs)
