### ISSUE TITLE
"Manage Certificate" option missing from "Configuration" menu

### ISSUE THREAD

**Issue by bries** [GluuFederation/docs#7]
Hi,

i'm trying to upload SSL certificates as per Admin Guide, but in my local install the "Manage Certificate" option does not exist.

I have found below errors in setup_error.log, but not sure if this is related.

Thanks
Bernd

04:22:34 03/10/15 log4j:ERROR setFile(null,true) call failed.
java.io.FileNotFoundException: /logs/oxauth_persistence_ldap_statistics.log (No such file or directory)
        at java.io.FileOutputStream.open(Native Method)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:142)
        at org.apache.log4j.FileAppender.setFile(FileAppender.java:289)
        at org.apache.log4j.FileAppender.activateOptions(FileAppender.java:163)
        at org.apache.log4j.DailyRollingFileAppender.activateOptions(DailyRollingFileAppender.java:215)
        at org.apache.log4j.config.PropertySetter.activate(PropertySetter.java:256)
        at org.apache.log4j.xml.DOMConfigurator.parseAppender(DOMConfigurator.java:220)
        at org.apache.log4j.xml.DOMConfigurator.findAppenderByName(DOMConfigurator.java:150)
        at org.apache.log4j.xml.DOMConfigurator.findAppenderByReference(DOMConfigurator.java:163)
        at org.apache.log4j.xml.DOMConfigurator.parseChildrenOfLoggerElement(DOMConfigurator.java:425)
        at org.apache.log4j.xml.DOMConfigurator.parseCategory(DOMConfigurator.java:345)
        at org.apache.log4j.xml.DOMConfigurator.parse(DOMConfigurator.java:827)
        at org.apache.log4j.xml.DOMConfigurator.doConfigure(DOMConfigurator.java:712)
        at org.apache.log4j.xml.DOMConfigurator.doConfigure(DOMConfigurator.java:618)
        at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:470)
        at org.apache.log4j.LogManager.<clinit>(LogManager.java:122)
        at org.apache.log4j.Logger.getLogger(Logger.java:117)
        at org.xdi.oxauth.model.util.JwtUtil.<clinit>(JwtUtil.java:84)
        at org.xdi.oxauth.model.crypto.signature.RSAPrivateKey.toJSONObject(RSAPrivateKey.java:57)
        at org.xdi.oxauth.model.crypto.Key.toJSONObject(Key.java:112)
        at org.xdi.oxauth.util.KeyGenerator.generateRS256Keys(KeyGenerator.java:54)
        at org.xdi.oxauth.util.KeyGenerator.main(KeyGenerator.java:26)
log4j:ERROR Either File or DatePattern options are not set for appender [OX_PERSISTENCE_LDAP_STATISTICS_FILE].
log4j:ERROR setFile(null,true) call failed.
java.io.FileNotFoundException: /logs/oxauth.log (No such file or directory)
        at java.io.FileOutputStream.open(Native Method)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:142)
        at org.apache.log4j.FileAppender.setFile(FileAppender.java:289)
        at org.apache.log4j.FileAppender.activateOptions(FileAppender.java:163)
        at org.apache.log4j.DailyRollingFileAppender.activateOptions(DailyRollingFileAppender.java:215)
        at org.apache.log4j.config.PropertySetter.activate(PropertySetter.java:256)
        at org.apache.log4j.xml.DOMConfigurator.parseAppender(DOMConfigurator.java:220)
        at org.apache.log4j.xml.DOMConfigurator.findAppenderByName(DOMConfigurator.java:150)
        at org.apache.log4j.xml.DOMConfigurator.findAppenderByReference(DOMConfigurator.java:163)
        at org.apache.log4j.xml.DOMConfigurator.parseChildrenOfLoggerElement(DOMConfigurator.java:425)
        at org.apache.log4j.xml.DOMConfigurator.parseRoot(DOMConfigurator.java:394)
        at org.apache.log4j.xml.DOMConfigurator.parse(DOMConfigurator.java:829)
        at org.apache.log4j.xml.DOMConfigurator.doConfigure(DOMConfigurator.java:712)
        at org.apache.log4j.xml.DOMConfigurator.doConfigure(DOMConfigurator.java:618)
        at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:470)
        at org.apache.log4j.LogManager.<clinit>(LogManager.java:122)
        at org.apache.log4j.Logger.getLogger(Logger.java:117)
        at org.xdi.oxauth.model.util.JwtUtil.<clinit>(JwtUtil.java:84)
        at org.xdi.oxauth.model.crypto.signature.RSAPrivateKey.toJSONObject(RSAPrivateKey.java:57)
        at org.xdi.oxauth.model.crypto.Key.toJSONObject(Key.java:112)
        at org.xdi.oxauth.util.KeyGenerator.generateRS256Keys(KeyGenerator.java:54)
        at org.xdi.oxauth.util.KeyGenerator.main(KeyGenerator.java:26)
log4j:ERROR Either File or DatePattern options are not set for appender [FILE].

**Comment by mzico** [comment]
Hi Bries, 

Yes, we lately removed this option from our Community Edition. May be in future we will add that again. 
For now, you need to manually update certificates and keys from /etc/certs/ location. "httpd.crt" and "httpd.key" are SSL keys for your Gluu Server CE. Here is how you can update the SSL httpd key and cert in Gluu CE: 

1. Push latest SSL httpd key and cert in /etc/certs. 
2. Rename them to "httpd.crt" and "httpd.key" respectively. 
3. Import the DER format of your cert in "cacert" ( location: /etc/pki/java/ ). 
4. Restart your Gluu-server from outside of chroot container.
